## 과제 수행자: 이세현

## 학번: 2025178869

In [1]:
import numpy as np


# Reading the example code

In [2]:
#Reading the example code
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [3]:
#Array fundamentals
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a[0]

1

In [5]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [6]:
a[:3]

array([10,  2,  3])

In [8]:
b = a[3:]
b


array([40,  5,  6])

In [9]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a[1, 3]

8

# Array attributes

In [12]:
a.ndim

2

In [13]:
a.shape
len(a.shape) == a.ndim

True

In [14]:
a.size
import math
a.size == math.prod(a.shape)

True

In [15]:
a.dtype

dtype('int64')

# How to create a basic array

In [16]:
np.zeros(2)

array([0., 0.])

In [17]:
np.ones(2)

array([1., 1.])

In [22]:


# 원소 2개짜리 빈 배열 생성
np.empty(2)
        # 실행 때마다 값이 달라짐

array([1., 1.])

In [20]:
np.arange(4)

array([0, 1, 2, 3])

In [23]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [24]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

# Adding, removing, and sorting elements

In [26]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [27]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [29]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [31]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

In [32]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [33]:
array_example.ndim

3

In [34]:
array_example.size

24

In [35]:
array_example.shape

(3, 2, 4)

# Can you reshape an array?

In [36]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [37]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [39]:
np.reshape(a, (1, 6), order='C')



array([[0, 1, 2, 3, 4, 5]])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [40]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [41]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [42]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [43]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [44]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [45]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [47]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and slicing

In [49]:
data = np.array([1, 2, 3])
data[1]

2

In [50]:
data[0:2]

array([1, 2])

In [51]:
data[1:]

array([2, 3])

In [52]:
data[-2:]

array([2, 3])

In [53]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [54]:
print(a[a < 5])

[1 2 3 4]


In [55]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [56]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [57]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [58]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [59]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [60]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [61]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [62]:
print(a[b])

[1 2 3 4]


In [63]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# How to create an array from existing data

In [64]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [66]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [67]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [68]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [69]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [70]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [71]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [72]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [73]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [74]:
b1[0] = 99


In [75]:
b1

array([99,  2,  3,  4])

In [76]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
b2 = a.copy()

# Basic array operations

In [78]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [79]:
data - ones
data * data
data / data

array([1., 1.])

In [80]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [81]:
b = np.array([[1, 1], [2, 2]])

In [82]:
b.sum(axis=0)

array([3, 3])

In [83]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

In [84]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

# More useful array operations

In [85]:
data.max()

2.0

In [86]:
data.min()

1.0

In [87]:
data.sum()

3.0

In [88]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [89]:
a.sum()

4.8595784

In [90]:
a.min()

0.05093587

In [91]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

# Creating matrices

In [92]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
data[0, 1]

2

In [94]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [95]:
data[0:2, 0]

array([1, 3])

In [96]:
data.max()

6

In [97]:
data.min()

1

In [98]:
data.sum()

21

In [99]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [100]:
data.max(axis=0)

array([5, 6])

In [101]:
data.max(axis=1)

array([2, 5, 6])

In [102]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [103]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [104]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [108]:
np.ones(3)

array([1., 1., 1.])

In [107]:
np.zeros(3)

array([0., 0., 0.])

In [109]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.63146685, 0.05174332, 0.22881701])

In [110]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [111]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [112]:
rng.random((3, 2)) 

array([[0.12251996, 0.78286004],
       [0.59012968, 0.32636011],
       [0.56083576, 0.87817371]])

# Generating random numbers

In [113]:
rng.integers(5, size=(2, 4)) 

array([[2, 0, 4, 1],
       [2, 3, 2, 4]])

# How to get unique items and counts

In [114]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [115]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [116]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [117]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [118]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [119]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [120]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [121]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


# Transposing and reshaping a matrix

In [122]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [124]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [125]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [126]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array

In [127]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [128]:
reversed_arr = np.flip(arr)

In [129]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [130]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [131]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [132]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [133]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [134]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [135]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Reshaping and flattening multidimensional arrays

In [136]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [137]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [138]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [139]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
